name: Build and Publish Pacakge.NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build package
      run: dotnet pack --configuration Release -o out
    - name: Publish package
      run: dotnet nuget push "out/*.nupkg" -k ${GITHUB_TOKEN} --source "https://nuget.pkg.github.com/bingla/index.json" --skip-duplicate 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
