name: Build and Test 

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: self-hosted
    env:
      CONFIG: 'Release'
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: 3.1.x
      
    - name: Restore Dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration $CONFIG --no-restore
      
    - name: Test
      run: dotnet test --configuration $CONFIG --no-restore --no-build --verbosity normal
