name: Build and Test 

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      config: 'Release'
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: 5.0.x
      
    - name: Restore Dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration $config --no-restore
      
    - name: Test
      run: dotnet test --configuration $config --no-build --no-restore --verbosity diagnostic
